name: Build Matrix

on:
  workflow_call:
    inputs:
      fail-fast:
        default: true
        type: boolean
      jobs:
        required: true
        type: string
      # Internal.
      cache_epoch:
        default: 'yee3Ain6'
        type: string
      cache_size:
        default: '128M'
        type: string
      ccache_version:
        default: '4.10.2'
        type: string
      ninjatracing_version:
        default: 'a669e3644cf22b29cbece31dbed2cfbf34e5f48e'
        type: string

defaults:
  run:
    shell: bash

jobs:

  Build:

    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        include: ${{ fromJSON(inputs.jobs) }}

    name: ${{ matrix.job }}
    runs-on: ${{ matrix.runs-on || 'ubuntu-latest' }}
    container: "${{ matrix.image && fromJSON(format('{{ \"image\": \"{0}\", \"options\": \"--user root\" }}', matrix.image)) || '' }}"

    env:
      BASH_ENV: '/root/.bashrc'
      CLICOLOR_FORCE: '1'
      CCACHE_DIR: "${{ format('{0}/ccache', github.workspace) }}"
      MAKEFLAGS: 'OUTPUT_DIR=build TARGET=${{ matrix.target }} ${{ matrix.makeflags }}'
      # Disable `tar` configure "safety" check when running as root…
      FORCE_UNSAFE_CONFIGURE: '1'

    steps:

      # Setup. {{{

      - name: Setup Python (macOS)
        if: runner.os == 'macOS'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup build environment (macOS)
        if: runner.os == 'macOS'
        run: |
          set -x
          # python packages
          python3 -m pip install --disable-pip-version-check meson ruamel.yaml
          # ninjatracing
          wget -O ninjatracing.zip https://github.com/nico/ninjatracing/archive/${{ inputs.ninjatracing_version }}.zip
          unzip -j ninjatracing.zip '*/ninjatracing'
          install -m755 ninjatracing /usr/local/bin/
          rm ninjatracing*
          # brew packages
          packages=(
            autoconf
            automake
            bash
            binutils
            cmake
            coreutils
            findutils
            libtool
            make
            nasm
            ninja
            pkg-config
            util-linux
          )
          # Don't auto-update.
          export HOMEBREW_NO_AUTO_UPDATE=1
          # Don't upgrade already installed formulas.
          export HOMEBREW_NO_INSTALL_UPGRADE=1
          # Remove some installed packages to prevent brew
          # from attempting (and failing) to upgrade them.
          brew uninstall gradle maven
          brew install --formula --overwrite --quiet "${packages[@]}"
          brew_paths=(
            "$(brew --prefix)/opt/findutils/libexec/gnubin"
            "$(brew --prefix)/opt/make/libexec/gnubin"
            "$(brew --prefix)/opt/util-linux/bin"
          )
          printf '%s\n' "${brew_paths[@]}" | tee -a "${GITHUB_PATH}"
          # ccache
          wget --progress=dot:mega https://github.com/ccache/ccache/releases/download/v${{ inputs.ccache_version }}/ccache-${{ inputs.ccache_version }}-darwin.tar.gz
          tar xf ccache-${{ inputs.ccache_version }}-darwin.tar.gz
          install -m755 ccache-${{ inputs.ccache_version }}-darwin/ccache /usr/local/bin/
          rm -rf ccache-*
          # xcode
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
          xcodebuild -version
          xcode-select -p
          # environment
          macos_env=(
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.macosx_deployment_target }}
          )
          printf '%s\n' "${macos_env[@]}" | tee -a "${GITHUB_ENV}"

      # }}}

      # Checkout / fetch. {{{

      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 1
          show-progress: false

      - name: Fix checkout ownership
        if: matrix.image
        run: chown 'root:root' .

      - name: Fetch
        run: make fetchthirdparty

      # }}}

      # Restore / setup caches. {{{

      - name: Generate cache key
        run: make TARGET= cache-key

      - name: Restore build directory
        id: build-restore
        uses: actions/cache/restore@v4
        with:
          path: build
          key: ${{ inputs.cache_epoch }}-${{ matrix.cache }}-build-${{ hashFiles('cache-key') }}

      - name: Lookup or restore build cache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ inputs.cache_epoch }}-${{ matrix.cache }}-ccache-${{ hashFiles('cache-key') }}
          restore-keys: ${{ inputs.cache_epoch }}-${{ matrix.cache }}-ccache-
          # When not building, do a lookup so the cache
          # does not get removed after 7 days with no use.
          lookup-only: ${{ steps.build-restore.outputs.cache-hit }}

      - name: Setup build cache
        if: steps.build-restore.outputs.cache-hit != 'true'
        run: |
          set -x
          which ccache
          ccache --version
          ccache --zero-stats
          ccache --max-size=${{ matrix.cache_size || inputs.cache_size }}
          ccache --show-config

      # }}}

      # Build. {{{

      - name: Build
        id: build
        if: steps.build-restore.outputs.cache-hit != 'true'
        run: make

      - name: Dump build timings
        if: contains('failure success', steps.build.conclusion) && !cancelled()
        run: make buildstats

      # }}}

      # Clean / save caches. {{{

      - name: Clean caches
        if: contains('failure success', steps.build.conclusion) && !cancelled()
        run: |
          set -x
          # Trim the build directory.
          rm -rf build/{cmake,staging,thirdparty}
          ccache --cleanup >/dev/null
          ccache --show-stats --verbose

      - name: Save build cache
        uses: actions/cache/save@v4
        if: steps.build-restore.outputs.cache-hit != 'true' && steps.ccache-restore.outputs.cache-hit != 'true'
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

      - name: Save build directory
        uses: actions/cache/save@v4
        if: steps.build-restore.outputs.cache-hit != 'true'
        with:
          path: build
          key: ${{ steps.build-restore.outputs.cache-primary-key }}

      # }}}

      # Dump & check binaries. {{{

      - name: Dump binaries runtime path & dependencies
        run: make bininfo

      - name: Checking binaries for missing dependencies
        run: make bincheck

      # }}}

      - name: Test
        if: matrix.test
        run: ./utils/fake_tty.py make --assume-old=all test

# vim: foldmethod=marker foldlevel=0
