name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    # Every Friday at 21:30 (UTC).
    - cron: '30 21 * * 4'
  workflow_dispatch:
    inputs:
      jobs:
        description: 'Run the specified list of job ids'
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
          sparse-checkout: .github/workflows
      - name: Generate outputs
        id: generate
        env:
          # Default jobs to run.
          base_jobs: >
            lint
            emu-clang emu-gcc-debug
            macos-arm64-14
            android-arm android-arm64
            kindlehf kindlepw2
            kobo
            pocketbook
          # Extra jobs when on master.
          master_extra_jobs: >
            emu-gcc
            macos-arm64-15
            macos-x86_64
            android-x86_64
            cervantes
            kindle kindle-legacy
        run: |
          set -o noglob
          jobs=(${{
            inputs.jobs && inputs.jobs ||
              (github.event.schedule && '.*' ||
                format('{0} {1}', env.base_jobs, github.ref == 'refs/heads/master' && env.master_extra_jobs || ''))
          }})
          set +o noglob
          >>"${GITHUB_OUTPUT}" .github/workflows/build.prepare.sh .github/workflows/build.jobs "${jobs[@]}"
    outputs:
      lint: ${{ steps.generate.outputs.lint }}
      emulator: ${{ steps.generate.outputs.emulator }}
      macos: ${{ steps.generate.outputs.macos }}
      platform: ${{ steps.generate.outputs.platform }}

  lint:
    name: Lint
    needs: prepare
    if: needs.prepare.outputs.lint
    runs-on: ubuntu-latest
    container:
      image: benoitpierre/kobase:0.4.0-22.04
    env:
      BASH_ENV: '/home/ko/.bashrc'
      CLICOLOR_FORCE: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
      - name: Lint
        run: .ci/lint_script.sh

  emulator:
    name: Emulator
    needs: [prepare, lint]
    if: |
      !cancelled() &&
      needs.prepare.outputs.emulator &&
      contains('skipped success', needs.lint.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.emulator }}
      fail_fast: true

  macos:
    name: macOS
    needs: [prepare, lint, emulator]
    if: |
      !cancelled() &&
      needs.prepare.outputs.macos &&
      contains('skipped success', needs.lint.result) &&
      contains('skipped success', needs.emulator.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.macos }}

  platform:
    name: Platform
    needs: [prepare, lint, emulator]
    if: |
      !cancelled() &&
      needs.prepare.outputs.platform &&
      contains('skipped success', needs.lint.result) &&
      contains('skipped success', needs.emulator.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.platform }}

# vim: foldmethod=marker foldlevel=0
